cote/urls.py
from django.urls import path, include
from .views import *
from . import views
app_name='cote'
urlpatterns = [

    path('exemplaire/', views.ExemplaireListView.as_view(permission_required='cote.view_exemplaire'),name='exemplaire'),
    path('exemplaire/<int:pk>/detail', views.ExemplaireDetailView.as_view(permission_required='cote.view_exemplaire'),name='exemplaire_detail'),
    path('exemplaire/create/', views.ExemplaireCreateView.as_view(permission_required='cote.add_exemplaire'),name='exemplaire_create'),
    path('exemplaire/<int:pk>/update/',views.ExemplaireUpdateView.as_view(permission_required='cote.change_exemplaire'), name='exemplaire_update'),
    path('exemplaire/<int:pk>/delete/',views.ExemplaireDeleteView.as_view(permission_required='cote.delete_exemplaire'), name='exemplaire_delete'),

    path('cote/', views.CoteListView.as_view(permission_required='cote.view_cote'),name='cote'),
    # path('cote/<int:pk>/detail', views.CoteDetailView.as_view(permission_required='cote.view_cote'),name='cote_detail'),
    # path('cote/create/', views.CoteCreateView.as_view(permission_required='cote.add_cote'),name='cote_create'),
    # path('cote/<int:pk>/update/',views.CoteUpdateView.as_view(permission_required='cote.change_cote'), name='cote_update'),
    # path('cote/<int:pk>/delete/',views.CoteDeleteView.as_view(permission_required='cote.delete_cote'), name='cote_delete'),

    path('deliberation/',deliberation, name='deliberation'),
    path('listdeliberation/',listdeliberation, name='listdeliberation'),
    path('listdeliberationone/',listdeliberationone, name='listdeliberationone'),

    path('addfile/',addfile, name='addfile'),
    path('corriger/',corriger, name='corriger'),
    path('deletefile/',deletefile, name='deletefile'),

]

inscription/urls.py
from django.urls import path, include
from .views import *
from . import views
app_name='inscription'

urlpatterns = [

    path('', check, name="check"),
    path('uncheck/', uncheck, name="uncheck"),
    path('home', TemplateMain.as_view(template_name='base.html'),name='home'),
    path('liste_candidat', CandidatListView.as_view(),name='listes_candidats'),
    path('candidat', CandidatsView.as_view(),name='candidats'),
    path('create', CandidatsView.as_view(),name='creates'),
    path('liste_par_anne/<str:anne>,<str:promotion>', get_candidat),
    path('paiement', Paiement.as_view(),name='paiement'),
    path('getpaiement',getpaiement,name='getpaiement'),
    path('getpaiement_all',getpaiement_all,name='getpaiement_all'),
    path('get_id_candidat/<str:id>',get_id_candidat),
    path('edit_etudiant',edit_etudiant,name='edit_etudiant'),
    path('desactive_candidat',desapprov,name='desapprov'),
    path('liste_candi_inactif',get_candidat_inactif,name='get_candidat_inactif'),
    path('index_inactif',index_inactif,name='index_inactif'),
    path('index_statistique',statistique_C,name='statistique_C'),
    path('statistique_candidat/<str:anne>,<str:valeur>',statique_candidat),
    path('imprimer_statistique',imprime_statistique,name="imprime_statistique"),
    path('imprimer_statistique_R',imprime_statistique_r,name="imprime_statistique_r"),
    path('imprime_inactif',imprime_inactif,name="imprime_inactif"),
    path('liste_candidats',liste_candidat,name="liste_candidats"),
    path('delete_paie_inscription',destroy_paie,name="delete_paie_candi"),
    
    #path('importation',edit_etudiant,name='edit_etudiant'),
    

]

paiement/urls.py
from django.urls import path, include
from .views import *
app_name='paiement'
urlpatterns = [

    path('', check, name="check"),
    path('uncheck/', uncheck, name="uncheck"),
    path('home', TemplateMain.as_view(template_name='base.html'),name='home'),
    path('paiement_frais', Paiement_fraisView.as_view(),name='paiement_frais'),
    path('edit_frais_classe', getfrais,name='getfrais'),
    path('paiements',Paiement_templateView.as_view(),name='get_paiements'),
    path('get_etudiant/<str:anne>,<str:promotion>',get_etudiant),
    path('get_tranche/<str:anne>,<str:promotion>,<str:frais>',get_tranche),
    path('get_montant',get_montant,name='get_montant'),
    path('delete_paie',delete_paie,name='delete_paie'),
    path('releve_paiement',Relevent.as_view(),name='releve_paiement'),
    path('delete_frais_classe',delete_frais_classe,name='delete_frais_classe'),
    path('get_releve/<str:anne>,<str:matricule>',get_releve),
    path('rapport_journalier',rapport_journalier,name='rapport_journalier'),
    path('get_rapportJ/<str:dates>,<str:datess>',get_rapportJ),
    path('liste_frais_classe',liste_frais,name='liste_frais'),
    path('liste_detail',liste_detail,name='liste_detail'),
    path('get_imprimer/<str:var_id>',get_imprimer),
    path('impression_situaation',print_situation,name="print_situation")
    
    

]

univa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parametrage.urls'), name='parametrage'),
    path('', include('cote.urls'), name='cote'),
    path('', include('inscription.urls'), name='inscription'),
    path('', include('paiement.urls'), name='inscription'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inscription/models.py
from django.db import models
from parametrage.models import Utilisat,annee,promotions

# Create your models here.
class TimespantedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True

Sexe = (
    ("F","Feminin"),
    ("M","Masculin")
    )
Etatcivil = (
    ("C","Célibataire"),
    ("M","Marié")
    )

class Fixation(models.Model):
    anne=models.ForeignKey(annee, models.PROTECT,editable=True,blank=True, null=True)
    libelle= models.CharField(max_length=60,blank=True, null=True)
    montant=models.DecimalField(max_digits=8,decimal_places=2,blank=True, null=True,default=0)
    etat=models.BooleanField(default=False)
    devise=models.CharField(max_length=5,blank=True, null=True)

    def __str__(self):
        return self.libelle
class Paimentinscription(TimespantedModel):
    prix=models.ForeignKey(Fixation, models.PROTECT,blank=True, null=True)
    code_candi=models.CharField(max_length=25,blank=True, null=True)
    observation=models.CharField(max_length=60,blank=True, null=True)
    montant=models.DecimalField(max_digits=8,decimal_places=2,blank=True, null=True,default=0)
    indice=models.CharField(max_length=1,blank=True, null=True,default="0")

    def __str__(self):
        return self.code_candi
class Candidat(TimespantedModel):
    nom = models.CharField(max_length=50)
    postnom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50,blank=True, null=True)
    sexe = models.CharField(choices=Sexe,max_length=1,default='M',blank=True, null=True)
    etat_civil = models.CharField(choices=Etatcivil, max_length=20,default='C',blank=True, null=True)
    telephone = models.CharField(max_length=15,blank=True, null=True)
    adresse = models.CharField(max_length=155, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    date_naissance = models.DateField(blank=True, null=True)
    lieu_naissance = models.CharField(max_length=100, blank=True, null=True)
    etat = models.BooleanField(default=True)
    user=models.ForeignKey(Utilisat, models.PROTECT,blank=True, null=True)
    reussie=models.CharField(max_length=1, blank=True, null=True,default="0")
    code=models.ForeignKey(Paimentinscription, models.PROTECT,editable=True,blank=True, null=True)
    
    def __str__(self):
        return self.nom

class Dossier(models.Model):
    candidat=models.ForeignKey(Candidat, models.PROTECT,blank=True, null=True)
    dossierss=models.ImageField(upload_to='img_candidat/',default=None,blank=True)

class Testadmin(models.Model):
     candidat=models.ForeignKey(Candidat, models.PROTECT,blank=True, null=True,related_name='candidatest')
     classe=models.ForeignKey(promotions, models.PROTECT,blank=True, null=True,related_name='codpromo')
     anne=models.ForeignKey(annee, models.PROTECT,blank=True, null=True)

paiement/models.py
from django.db import models
from parametrage.models import  Utilisat,annee,promotions,etudiants

# Create your models here.
class TimespantedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract=True
class Frais(models.Model):
    type=models.CharField(max_length=30,unique=True,blank=True,null=True) 

    def __str__(self):
        return self.type

class Fraisclasse(TimespantedModel):
    anne=models.ForeignKey(annee, models.PROTECT,blank=True, null=True)
    promotion=models.ForeignKey(promotions, models.PROTECT,blank=True, null=True,related_name='codpromos')
    frais=models.ForeignKey(Frais, models.PROTECT,blank=True, null=True,related_name='fraiscl')
    devise=models.CharField(max_length=5,blank=True, null=True)
    montant=models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)

class Fraistranche(TimespantedModel):
    tranche=models.CharField(max_length=20,blank=True, null=True)
    montant=models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    devise=models.CharField(max_length=5,blank=True, null=True)
    fraistranche=models.ForeignKey(Fraisclasse, models.PROTECT,blank=True, null=True)

class Paiement_frais(TimespantedModel):
    code_paie= models.CharField(max_length=20,blank=True, null=True,unique=True)
    matricule=models.ForeignKey(etudiants, models.PROTECT,blank=True, null=True,related_name='paie_etudiant')
    tranche=models.ForeignKey(Fraistranche, models.PROTECT,blank=True, null=True,related_name='paie_tranche')
    anne=models.ForeignKey(annee, models.PROTECT,blank=True, null=True)
    montantpaie=models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    user=models.ForeignKey(Utilisat, models.PROTECT,blank=True, null=True) 
    frais=models.ForeignKey(Frais, models.PROTECT,blank=True, null=True)

class Impression_paie(models.Model):
    dateOp =models.DateField(blank=True, null=True)
    code_paie= models.CharField(max_length=20,blank=True, null=True,unique=True)
    montlettre = models.CharField(max_length=255,blank=True, null=True)
    totalfrais = models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    totalreste = models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    totalpaye = models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    totaltranche = models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    montantpaie=models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    frais=models.ForeignKey(Frais, models.PROTECT,blank=True, null=True)
    user=models.ForeignKey(Utilisat, models.PROTECT,blank=True, null=True)
    matricule=models.ForeignKey(etudiants, models.PROTECT,blank=True, null=True,related_name='paie_etudiants')
    anne=models.ForeignKey(annee, models.PROTECT,blank=True, null=True) 
    promotion=models.ForeignKey(promotions, models.PROTECT,blank=True, null=True,related_name='promotions')
    devise=models.CharField(max_length=5,blank=True, null=True)
    tranche=models.ForeignKey(Fraistranche, models.PROTECT,blank=True, null=True,related_name='paie_tranches')

inscription/templates/candidat.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock %}


{% block content %}

 <div class="container-fluid pt-4 px-4">
                <div class="row vh-50 bg-secondary rounded mx-0">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Ajout Candidat</h6>
                            {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-dismissible alert-success">
                                <strong>{{message}}</strong>
                                </div>
                            {% endfor %}
                            {% endif %}
                            <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                                         <div class="row mb-3">

                                    <div class="col-sm-6">
                                           <label class="form-label">Annee Academique</label>
                                            <select class="form-control select" id="annee" name="annee">
                                                <option value="-1">Choisir année</option>
                                                {% for foo in annee %}
                                                <option value="{{ foo.id }}"selected>{{ foo.libelle }}</option>
                                                {% endfor %}
                                            </select>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="exampleInputEmail1" class="form-label">Promotion</label>
                                        <select  class="form-control required select" id="promotion" name="promotion">
                                            <option value="-1">Choisir année</option>
                                            {% for foo in promotion %}
                                            <option value="{{ foo.id }}">{{ foo.libelle }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="inputEmail3" class="col-sm-2 col-form-label">Code Candidat</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="code" id="code" required>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Nom Candidat</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="name" id="name" required>
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Post-Nom</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="pastname" id="pastname" required>
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Prenom</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="Prenom" id="Prenom" required>
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Sexe</label>
                                    <div class="col-sm-4">
                                        <select class="form-control select" id="sexe" name="sexe" required>
                                            <option value="M" selected>Masculin</option>
                                            <option value="F">Feminin</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Etat civil</label>
                                    <div class="col-sm-4">
                                        <select class="form-control select" id="etatciv" name="etatciv" required>
                                            <option value="C" selected>Celibataire</option>
                                            <option value="M">Marié</option>
                                        </select>
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Date de Naissance</label>
                                    <div class="col-sm-10">
                                        <input type="date" class="form-control" name="datnaisse" id="datnaisse" {% now "d-m-Y" %} required>
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Lieu de Naissance</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="lieu" id="lieu" required>
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Télephone</label>
                                    <div class="col-sm-10">
                                        <input type="tel" class="form-control" name="telephone" id="telephone" required>
                                        <small>Format: 123-456-7890</small>
                                    </div>
                                   
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Adresse</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="adresse" id="adresse" required>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Dossier</label>
                                    <div class="col-sm-10">
                                        <input type="file" accept="image/*" name ="img_dossier" multiple class="form-control"  id="img_dossier" required>
                                    </div>
                                </div>
                            <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Etat</label>
                                    <div class="col-sm-10">
                                        <input class="form-check-input m-0" checked name="etat" id="id_etat" type="checkbox">

                                    </div>
                                </div>
                                <div class="col-sm-12">
                                <button type="submit" class="btn btn-primary" name="_addanothers">Enregistrer</button>
                                <button type="reset" class="btn btn-danger" name="_save">Annuler</button>
                                <button type="button" onclick="window.location='{% url 'inscription:listes_candidats' %}'; return false;" class="btn btn-outline-warning">Voir la liste</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
 </div>

{% endblock %}


 {% block script %}

    <script>
        (function() {
            $('.select').select2();
            $("#telephone").on('input', function(){
                if(isNaN($("#telephone").val())){
                    $("#telephone").val('');
                }
            })

        })();








    </script>
{% endblock %}

inscription/templates/liste_candidat_inactif.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock %}
{% block content %}

<div class="container-fluid pt-4 px-4">
    <div class="row vh-50 bg-secondary rounded align-items-center justify-content-center mx-0">
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content backgroundColor-transparent">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  ...
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
          </div>
       <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Candidat </h6>
                <form id="form1">
                    {% csrf_token %}

                  
                </form>
                <div class="accordion" id="accordionExample">
                    <div class="accordion-item bg-transparent">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                Liste des Candidat inactif
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
                            <div class="accordion-body">

                                <div class="table-responsive">
                                    <table id="tab_candidat" class="table table-hover dataTable table-striped table_custom border-style spacing5">
                                        <thead>
                                            <tr>
                                            <th>#</th>
                                            <th>Année</th>
                                            <th>Promo</th>
                                            <th>code</th>
                                            <th width="150">Nom</th>
                                            <th>Postnom</th>
                                            <th>Prenom</th>
                                            <th>Sexe</th>
                                            <th width="150">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tbody" style="color: white">
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                        <div class="col-sm-8">
                        <button  type="button" id="print" class="btn btn-primary">Imprimer</button>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}

<script>
    (function() {
        $('.select').select2();
        $("#telephone").on('input', function(){
            if(isNaN($("#telephone").val())){
                $("#telephone").val('');
            }
        })
        affiche_entree();
        $('#tab_candidat').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'print', 'copy', 'excel', 'pdf'
            ],
            "bProcessing": true,
            order:[[0,"DESC"]],
             "pageLength": 10,
             "bDestroy":true
        });


        $('body').delegate('.editcandidat','click',function(e){
            var idd=$(this).data('id');
            window.location.href = ("/get_id_candidat/" + idd);

        });

        $('body').delegate('.check','click',function(e){
            var idd=$(this).data('id');
            Swal.fire({
                title: 'Univa Application',
                html: "voulez vous que que ce candidat(e) devienne actif(ve)",
                width: 600,
                padding: '3em',
                showDenyButton: true,
                confirmButtonText: `Enregistrer`,
                denyButtonText: `Annuler`,
            }).then((result) =>{
                if(result.isConfirmed){
                        $.ajax({
                            url:"{% url 'inscription:desapprov' %}",
                            type:"POST",
                            async: true,
                            data:{id:idd,
                                  annee:$('#annee').val(),
                                  promotion:$('#promotion').val(),
                                  csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                                },
                            success:function(response){
                                if(response.status == 200){
                                    window.location.reload(); 
                                }
                                else{
                                    Swal.fire('Univa Application', 'operation annuler', 'error')
                                }
                            },
                            error:function(response){
                                console.log(response.success);
                            }
                        });
                   
                  
                       

                }
                else if(result.isDenied){
                    Swal.fire('Univa Application', 'operation echoué', 'error')
                }
            });

        });
        $('#print').click(function(){

            if(!$('#tab_candidat tr').length == 0 ){
                $.ajax({
                    url: "{% url 'inscription:imprime_inactif' %}",
                    type: "POST",
                    async: true,
                    data:{
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function(response){
                        if(response =="true"){
                             window.open('{{ MEDIA_URL }}candidat_inactif.pdf');
                             }

                    },
                    error: function(request, status, err) {
                        alert((status == "timeout") ? "Timeout" : "error: " + request + status + err);
                    }
                   })
            }
        });

    })();

    function affiche_entree() {
        var otableau = $('#tab_candidat').DataTable({
           dom: 'Bfrtip',
           buttons: [
              'print', 'copy', 'excel', 'pdf'
           ],
           "bProcessing": true,
           "sAjaxSource": "{% url 'inscription:get_candidat_inactif' %}",
           "columns": [{
                 "data": 'id'
              },
              {
                 "data": 'anne__libelle'
              },
              {
                 "data": 'classe__libelle'
              },
              {
                "data": 'candidat__code__code_candi'
             },
             {
                "data": 'candidat__nom'
             },
             {
                "data": 'candidat__postnom'
             },
              {
                 "data": 'candidat__prenom'
              },
              {
                "data": 'candidat__sexe'
             },
           
              {
                 "data": 'id',
                 "autoWidth": true,
                 "render": function(data) {
                    return '<button data-id='+data+' class="btn btn-success btn-circle editcandidat"><i class="fa fa-edit"></i></button> <button data-id='+data+' class="btn btn-success btn-circle check"><i class="fa fa-check"></i></button>';
                 }
              }
  
           ],
           "bProcessing": true,
            order:[[0,"DESC"]],
            "pageLength": 10,
            "bDestroy":true
        });
  
     }






</script>
{% endblock %}