cote/urls.py
from django.urls import path, include
from .views import *
from . import views
app_name='cote'
urlpatterns = [

    path('exemplaire/', views.ExemplaireListView.as_view(permission_required='cote.view_exemplaire'),name='exemplaire'),
    path('exemplaire/<int:pk>/detail', views.ExemplaireDetailView.as_view(permission_required='cote.view_exemplaire'),name='exemplaire_detail'),
    path('exemplaire/create/', views.ExemplaireCreateView.as_view(permission_required='cote.add_exemplaire'),name='exemplaire_create'),
    path('exemplaire/<int:pk>/update/',views.ExemplaireUpdateView.as_view(permission_required='cote.change_exemplaire'), name='exemplaire_update'),
    path('exemplaire/<int:pk>/delete/',views.ExemplaireDeleteView.as_view(permission_required='cote.delete_exemplaire'), name='exemplaire_delete'),

    path('cote/', views.CoteListView.as_view(permission_required='cote.view_cote'),name='cote'),
    # path('cote/<int:pk>/detail', views.CoteDetailView.as_view(permission_required='cote.view_cote'),name='cote_detail'),
    # path('cote/create/', views.CoteCreateView.as_view(permission_required='cote.add_cote'),name='cote_create'),
    # path('cote/<int:pk>/update/',views.CoteUpdateView.as_view(permission_required='cote.change_cote'), name='cote_update'),
    # path('cote/<int:pk>/delete/',views.CoteDeleteView.as_view(permission_required='cote.delete_cote'), name='cote_delete'),

    path('deliberation/',deliberation, name='deliberation'),
    path('listdeliberation/',listdeliberation, name='listdeliberation'),
    path('listdeliberationone/',listdeliberationone, name='listdeliberationone'),

    path('addfile/',addfile, name='addfile'),
    path('corriger/',corriger, name='corriger'),
    path('deletefile/',deletefile, name='deletefile'),

]

paiement/urls.py
from django.urls import path, include
from .views import *
app_name='paiement'
urlpatterns = [

    path('', check, name="check"),
    path('uncheck/', uncheck, name="uncheck"),
    path('home', TemplateMain.as_view(template_name='base.html'),name='home'),
    path('paiement_frais', Paiement_fraisView.as_view(),name='paiement_frais'),
    path('edit_frais_classe', getfrais,name='getfrais'),
    path('paiements',Paiement_templateView.as_view(),name='get_paiements'),
    path('get_etudiant/<str:anne>,<str:promotion>',get_etudiant),
    path('get_tranche/<str:anne>,<str:promotion>,<str:frais>',get_tranche),
    path('get_montant',get_montant,name='get_montant'),
    path('delete_paie',delete_paie,name='delete_paie'),
    path('releve_paiement',Relevent.as_view(),name='releve_paiement'),
    path('delete_frais_classe',delete_frais_classe,name='delete_frais_classe'),
    path('get_releve/<str:anne>,<str:matricule>',get_releve),
    path('rapport_journalier',rapport_journalier,name='rapport_journalier'),
    path('get_rapportJ/<str:dates>,<str:datess>',get_rapportJ),
    path('liste_frais_classe',liste_frais,name='liste_frais'),
    path('liste_detail',liste_detail,name='liste_detail'),
    path('get_imprimer/<str:var_id>',get_imprimer),
    path('impression_situaation',print_situation,name="print_situation")
    
    

]

univa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parametrage.urls'), name='parametrage'),
    path('', include('cote.urls'), name='cote'),
    path('', include('inscription.urls'), name='inscription'),
    path('', include('paiement.urls'), name='inscription'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paiement/models.py
from django.db import models
from parametrage.models import  Utilisat,annee,promotions,etudiants

# Create your models here.
class TimespantedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract=True
class Frais(models.Model):
    type=models.CharField(max_length=30,unique=True,blank=True,null=True) 

    def __str__(self):
        return self.type

class Fraisclasse(TimespantedModel):
    anne=models.ForeignKey(annee, models.PROTECT,blank=True, null=True)
    promotion=models.ForeignKey(promotions, models.PROTECT,blank=True, null=True,related_name='codpromos')
    frais=models.ForeignKey(Frais, models.PROTECT,blank=True, null=True,related_name='fraiscl')
    devise=models.CharField(max_length=5,blank=True, null=True)
    montant=models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)

class Fraistranche(TimespantedModel):
    tranche=models.CharField(max_length=20,blank=True, null=True)
    montant=models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    devise=models.CharField(max_length=5,blank=True, null=True)
    fraistranche=models.ForeignKey(Fraisclasse, models.PROTECT,blank=True, null=True)

class Paiement_frais(TimespantedModel):
    code_paie= models.CharField(max_length=20,blank=True, null=True,unique=True)
    matricule=models.ForeignKey(etudiants, models.PROTECT,blank=True, null=True,related_name='paie_etudiant')
    tranche=models.ForeignKey(Fraistranche, models.PROTECT,blank=True, null=True,related_name='paie_tranche')
    anne=models.ForeignKey(annee, models.PROTECT,blank=True, null=True)
    montantpaie=models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    user=models.ForeignKey(Utilisat, models.PROTECT,blank=True, null=True) 
    frais=models.ForeignKey(Frais, models.PROTECT,blank=True, null=True)

class Impression_paie(models.Model):
    dateOp =models.DateField(blank=True, null=True)
    code_paie= models.CharField(max_length=20,blank=True, null=True,unique=True)
    montlettre = models.CharField(max_length=255,blank=True, null=True)
    totalfrais = models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    totalreste = models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    totalpaye = models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    totaltranche = models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    montantpaie=models.DecimalField(max_digits=10,decimal_places=2,blank=True, null=True,default=0)
    frais=models.ForeignKey(Frais, models.PROTECT,blank=True, null=True)
    user=models.ForeignKey(Utilisat, models.PROTECT,blank=True, null=True)
    matricule=models.ForeignKey(etudiants, models.PROTECT,blank=True, null=True,related_name='paie_etudiants')
    anne=models.ForeignKey(annee, models.PROTECT,blank=True, null=True) 
    promotion=models.ForeignKey(promotions, models.PROTECT,blank=True, null=True,related_name='promotions')
    devise=models.CharField(max_length=5,blank=True, null=True)
    tranche=models.ForeignKey(Fraistranche, models.PROTECT,blank=True, null=True,related_name='paie_tranches')

paiement/views.py
from multiprocessing import context
from operator import concat
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.views import View
from parametrage.models import annee,promotions,etudiants
from .models import *
from django.db.models.functions import Concat
from cote.models import etudprom
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.db.models import Sum,Value
import shortuuid
from num2words import num2words
from datetime import date,datetime
from inscription.views import lienImage
from pyreportjasper import JasperPy
import os
from django.conf import settings
# Create your views here.
fn = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
class TemplateMain(LoginRequiredMixin,TemplateView):
    pass
def check(request):
    
    if request.user.username:
         return redirect(reverse('parametrage:home'))

    if request.method=='GET':
        return render(request, 'login.html')
    username = request.POST['username']
    password = request.POST['pass']
    user = authenticate(username=username, password=password)
    if user is not None and user.is_active:
        login(request, user)
        return redirect(reverse('parametrage:home'))
    else:
        return redirect(reverse('parametrage:check'))

@login_required
def uncheck(request):
    logout(request)
    return redirect(reverse('parametrage:check'))

class Paiement_fraisView(View):
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            try:
                result=Fraisclasse.objects.get(anne_id=self.request.POST.get('anee'),promotion_id=self.request.POST.get('promotion'),frais_id=self.request.POST.get('frais'))
                if result:
                    nbre=int(self.request.POST.get('nbre'))
                    if nbre == 1:
                        montant=float(self.request.POST.get('Montant'))
                        requette=Fraistranche.objects.get(fraistranche_id=result.id)
                        if requette:
                            indice='plage'+ str(requette.id)
                            if self.request.POST.get(indice) is not None:
                                tranche=float(self.request.POST.get(indice))
                                if montant == tranche:
                                    result.montant=self.request.POST.get('Montant')
                                    result.devise=self.request.POST.get('devise')
                                    requette.montant=tranche
                                    requette.devise=self.request.POST.get('devise')
                                    requette.save()
                                    result.save() 
                                    messages.success(request, 'modification avec succes')
                                    return redirect(reverse('paiement:paiement_frais'))
                            else:
                                messages.error(request, 'veuillez verifier votre repartition')
                                return redirect(reverse('paiement:paiement_frais'))
                                
                    elif nbre > 0:
                        montant=float(self.request.POST.get('Montant'))
                        requette=Fraistranche.objects.filter(fraistranche_id=result.id)
                        tranche=0
                        for ligne in requette:
                            indice ='plage'+ str(ligne.id)
                            tranche +=float(self.request.POST.get(indice))
                        if montant == tranche:
                            result.montant=self.request.POST.get('Montant')
                            result.devise=self.request.POST.get('devise')
                            result.save()
                            for ligne in requette:
                                indice='plage'+str(ligne.id)
                                ligne.montant=self.request.POST.get(indice)
                                ligne.devise=self.request.POST.get('devise')
                                ligne.save()
                                
                            messages.success(request, 'modification avec succes')
                            return redirect(reverse('paiement:paiement_frais'))
                        else:
                            messages.error(request, 'le montant de la tranche doit etre egal au montant de frais')
                            return redirect(reverse('paiement:paiement_frais'))
                                
                                    
            except Fraisclasse.DoesNotExist:
                result=None
                nbre=int(self.request.POST.get('nbre'))
                if nbre == 1:
                    if self.request.POST.get('plage1') and self.request.POST.get('plage1') is not None:
                        montant=float(self.request.POST.get('Montant'))
                        tranche=float(self.request.POST.get('plage1'))
                        if montant == tranche:
                            result=Fraisclasse(
                            anne_id=self.request.POST.get('anee'),
                            promotion_id=self.request.POST.get('promotion'),
                            frais_id=self.request.POST.get('frais'),
                            montant=self.request.POST.get('Montant'),
                            devise=self.request.POST.get('devise'))
                            result.save()
                            requette=Fraistranche(
                                tranche='1er Tranche',
                                montant=self.request.POST.get('plage1'),
                                devise=self.request.POST.get('devise'),
                                fraistranche_id=result.id   
                            )
                            requette.save()
                            messages.success(request, 'Frais Classe ajoutée')
                            return redirect(reverse('paiement:paiement_frais'))
                       
                    else:
                        messages.error(request, 'verifier bien votre repartition')
                        return redirect(reverse('paiement:paiement_frais'))
                elif nbre > 1:
                    montant=float(self.request.POST.get('Montant'))
                    tranche=0
                    nbre+=1
                    for i in range(1,nbre):
                        indice='plage'+str(i)
                        tranche +=float(self.request.POST.get(indice))
                    
                    if montant == tranche:
                        result=Fraisclasse(
                           anne_id=self.request.POST.get('anee'),
                           promotion_id=self.request.POST.get('promotion'),
                           frais_id=self.request.POST.get('frais'),
                           montant=self.request.POST.get('Montant'),
                           devise=self.request.POST.get('devise'))
                        result.save()
                        for i in range(1,nbre):
                            indice='plage' + str(i)
                            libtranche =''
                            if i== 1:
                                libtranche ='1er Tranche'
                            elif i== 2:
                                 libtranche ='2eme Tranche'
                            else:
                                libtranche ='3eme Tranche'
                                
                            requette=Fraistranche(
                            tranche=libtranche,
                            montant=self.request.POST.get(indice),
                            devise=self.request.POST.get('devise'),
                            fraistranche_id=result.id   
                            )
                            requette.save()
                            
                        messages.success(request, 'Frais Classe ajoutée')
                        return redirect(reverse('paiement:paiement_frais')) 
                    else:
                        messages.error(request, 'la repartition de tranche doit correspondre au montant de la promotion')
                        return redirect(reverse('paiement:paiement_frais'))        
    
    def get(self, request, *args, **kwargs):
        context={
            "annee":annee.objects.filter(etat=True),
            "promotion":promotions.objects.filter(etat=True),
            "frais":Frais.objects.all(),
            "Frais_classe":Fraisclasse.objects.all().values('id','anne__libelle','promotion__libelle','frais__type','devise','montant').order_by('-id'),
        }
        return render(request,"form_frais_classe.html",context)

def getfrais(request):
    result=Fraisclasse.objects.filter(pk=request.POST.get('id')).values('id','anne_id','promotion_id','frais_id','devise','montant')
    result1=Fraistranche.objects.filter(fraistranche_id=request.POST.get('id')).values('id','montant',)
    data={
        "frais_classe":list(result),
        "frais_tranche":list(result1)
    }
    return JsonResponse(data,safe=False)

def delete_frais_classe(request):
    result=Fraistranche.objects.filter(fraistranche_id=request.POST.get('id')).delete()
    resultd=Fraisclasse.objects.filter(id=request.POST.get('id')).delete()
    return JsonResponse({'status':200},safe=False)


class Paiement_templateView(View):
    def get(self, request, *args, **kwargs):
        s = shortuuid.ShortUUID(alphabet="0123456789")
        otp = s.random(length=5)
        context={

paiement/templates/rapport_jour.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock %}


{% block content %}

 <div class="container-fluid pt-4 px-4">
                <div class="row vh-50 bg-secondary rounded mx-0">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Rapport de Paiement</h6>
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-dismissible alert-success">
                                    <strong>{{message}}</strong>
                                    </div>
                                {% endfor %}
                                {% endif %}
                            <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                           
                                <div class="row mb-3">
                                    <div class="col-sm-6">
                                    <label class="form-label">Du </label>
                                        <input type="date" class="form-control" name="datepaie" id="datepaie_du" {% now "d-m-Y" %} required>
                                    </div>
                                    <div class="col-sm-6">
                                        <label class="form-label">Au </label>
                                            <input type="date" class="form-control" name="datepaie" id="datepaie_au" {% now "d-m-Y" %} required>
                                        </div>
                            </div>
                            <div class="col-sm-12">
                                <button type="button" class="btn btn-primary" id="addanothers">Afficher le rapport </button>
                                <button type="button" class="btn btn-danger" name="_save" id='print_rapport'>Imprimer le rapport</button>
                            </div>
                            </form></br></br>
                            <div class="accordion" id="accordionExample">
                                <div class="accordion-item bg-transparent">
                                    <h2 class="accordion-header" id="headingOne">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                            Liste de paiement de frais
            
                                        </button>
                                    </h2>
                                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
                                        <div class="accordion-body">
        
                                            <div class="table-responsive">
                                                <table id="tab_releves" class="table table-hover dataTable table-striped table_custom border-style spacing5">
                                                    <thead>
                                                        <tr>
                                                        <th>#</th>
                                                        <th>date</th>
                                                        <th>Annee</th>
                                                        <th width="150">Promotion</th>
                                                        <th width="150">Frais</th>
                                                        <th>Tranche</th>
                                                        <th >devise</th>
                                                        <th>Montant</th>
                                                        <th width="300">Etudiant</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody id="tbody" style="color: white">
                                                      
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
 </div>

{% endblock %}


{% block script %}

<script>
    let var_int=0;
    (function() {
$('.select').select2();
let date1=new Date().toLocaleDateString('en-GB');
get_motant_releve(code=[date1.split('/').reverse().join("-"), date1.split('/').reverse().join("-")]);
$('#addanothers').click(function(){
    if($('#datepaie_du').val() != '' && $('#datepaie_au').val() != ''){
        var dates = $('#datepaie_du').val();
        var dates_au = $('#datepaie_au').val();
        var newdate=dates.split('/').reverse().join("-");
        var newdates=dates_au.split('/').reverse().join("-");
        get_motant_releve(code=[newdate,newdates]);
    }
});

$('#print_rapport').click(function(){
    if($('#datepaie_du').val() != '' && $('#datepaie_au').val() != ''){
        var dates = $('#datepaie_du').val();
        var dates_au = $('#datepaie_au').val();
        var newdate=dates.split('/').reverse().join("-");
        var newdates=dates_au.split('/').reverse().join("-");
        $.ajax({
            url: "{% url 'paiement:print_situation' %}",
            type: 'POST',
            async: false,
            data:{
                date_du:$('#datepaie_du').val(),
                date_au:$('#datepaie_au').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(response){
                if(response == "true"){
                    window.open('{{ MEDIA_URL }}situation_paie.pdf');
                }

            },
            error: function(request, status, err) {
                alert((status == "timeout") ? "Timeout" : "error: " + request + status + err);
            }
        })
    }
    Swal.fire("Univa","veuillez selectionner les dates","info")

});




function get_motant_releve(code=[]){
    var otableau=$('#tab_releves').DataTable({
        "bProcessing":true,
        "sAjaxSource":"/get_rapportJ/"+code,
        "columns":[
            {"data":'id'},
            {"data":'created_at',"autoWidth":true,"render":function (data){
                const result = new Date(data).toLocaleDateString('en-GB');
                return result;
            }},
            {"data":'anne__libelle'},
            {"data":'tranche__fraistranche__promotion__libelle'},
            {"data":'frais__type'},
            {"data":'tranche__tranche'},
            {"data":'tranche__devise'},
            {"data":'montantpaie'},
            {"data":'names'},   
        ],
        "pageLength": 10, 
        "bDestroy":true,
        order:[[0,"DESC"]],
    });
}
    })();
</script>
{% endblock %}