cote/urls.py
from django.urls import path, include
from .views import *
from . import views
app_name='cote'
urlpatterns = [

    path('exemplaire/', views.ExemplaireListView.as_view(permission_required='cote.view_exemplaire'),name='exemplaire'),
    path('exemplaire/<int:pk>/detail', views.ExemplaireDetailView.as_view(permission_required='cote.view_exemplaire'),name='exemplaire_detail'),
    path('exemplaire/create/', views.ExemplaireCreateView.as_view(permission_required='cote.add_exemplaire'),name='exemplaire_create'),
    path('exemplaire/<int:pk>/update/',views.ExemplaireUpdateView.as_view(permission_required='cote.change_exemplaire'), name='exemplaire_update'),
    path('exemplaire/<int:pk>/delete/',views.ExemplaireDeleteView.as_view(permission_required='cote.delete_exemplaire'), name='exemplaire_delete'),

    path('cote/', views.CoteListView.as_view(permission_required='cote.view_cote'),name='cote'),
    # path('cote/<int:pk>/detail', views.CoteDetailView.as_view(permission_required='cote.view_cote'),name='cote_detail'),
    # path('cote/create/', views.CoteCreateView.as_view(permission_required='cote.add_cote'),name='cote_create'),
    # path('cote/<int:pk>/update/',views.CoteUpdateView.as_view(permission_required='cote.change_cote'), name='cote_update'),
    # path('cote/<int:pk>/delete/',views.CoteDeleteView.as_view(permission_required='cote.delete_cote'), name='cote_delete'),

    path('deliberation/',deliberation, name='deliberation'),
    path('listdeliberation/',listdeliberation, name='listdeliberation'),
    path('listdeliberationone/',listdeliberationone, name='listdeliberationone'),

    path('addfile/',addfile, name='addfile'),
    path('corriger/',corriger, name='corriger'),
    path('deletefile/',deletefile, name='deletefile'),

]

univa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parametrage.urls'), name='parametrage'),
    path('', include('cote.urls'), name='cote'),
    path('', include('inscription.urls'), name='inscription'),
    path('', include('paiement.urls'), name='inscription'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cote/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from parametrage.models import promotions,annee,etudiants,TimespantedModel,cours,Utilisat,sessions
# Create your models here.

categorie = (
    (1,"Matières de formation professionnelle"),
    (2,"Matières d'appui formation professionnelle"),
    (3,"Matières de formation générale"),

    )
class etudprom(TimespantedModel):
    matricule = models.ForeignKey(etudiants, models.PROTECT)
    promotion = models.ForeignKey(promotions, models.PROTECT)
    annee = models.ForeignKey(annee, models.PROTECT)
    mi_session = models.IntegerField(default=1)
    mention_mi_session = models.CharField(max_length=100, blank=True, null=True)
    pourc_mi_session = models.FloatField(blank=True, null=True)
    one_session = models.IntegerField(default=2)
    mention_one_session = models.CharField(max_length=100, blank=True, null=True)
    pourc_one_session = models.FloatField(blank=True, null=True)
    two_session = models.IntegerField(default=3)
    mention_two_session = models.CharField(max_length=100, blank=True, null=True)
    pourc_two_session = models.FloatField(blank=True, null=True)
    trav = models.FloatField(blank=True, null=True)
    stag = models.FloatField(blank=True, null=True)

    class Meta:
       unique_together=['matricule', 'promotion','annee']

class exemplaire(TimespantedModel):
    matricule = models.ForeignKey(etudiants, models.PROTECT)
    lien=models.CharField(max_length=255)
    user = models.ForeignKey(Utilisat, models.PROTECT)
    promotion = models.ForeignKey(promotions, models.PROTECT)
    annee = models.ForeignKey(annee, models.PROTECT)
    cours = models.ForeignKey(cours, models.PROTECT)
    sesionn = models.CharField(choices=sessions,max_length=1)
    numero = models.IntegerField(default=1)

    class Meta:
        unique_together=['matricule', 'promotion','cours','annee','sesionn','numero']

class cote(TimespantedModel):
    matricule = models.ForeignKey(etudiants, models.PROTECT)
    lien=models.CharField(max_length=255,null=True,blank=True)
    user = models.ForeignKey(Utilisat, models.PROTECT)
    promotion = models.ForeignKey(promotions, models.PROTECT)
    annee = models.ForeignKey(annee, models.PROTECT)
    cours = models.ForeignKey(cours, models.PROTECT)
    sesionn = models.CharField(choices=sessions,max_length=1)
    numero = models.IntegerField(default=1)
    cote = models.FloatField()



    class Meta:
        unique_together=['matricule', 'promotion','cours','annee','sesionn','numero']

class delibe(TimespantedModel):
    opde = models.CharField(max_length=5)
    de = models.FloatField()
    opa = models.CharField(max_length=5)
    a = models.FloatField()
    etat= models.CharField(max_length=10)
    op= models.CharField(max_length=5)
    nbr= models.IntegerField()
    position= models.IntegerField()

    class Meta:
        verbose_name = 'Règle Déliberation'
        verbose_name_plural = 'Règle Déliberation'
        unique_together=['opde', 'de','opa','a','etat','op','nbr','position']

class delibedetail(TimespantedModel):
    annee = models.ForeignKey(annee, models.PROTECT)
    dateop = models.DateField()
    president = models.CharField(max_length=255)
    secretaire1 = models.CharField(max_length=255)
    secretaire2 = models.CharField(max_length=255)
    membres = models.CharField(max_length=255)


class tempjournalcote(TimespantedModel):
    matricule = models.ForeignKey(etudiants, models.PROTECT)
    lien=models.CharField(max_length=255)
    obs=models.CharField(max_length=255)
    user = models.ForeignKey(Utilisat, models.PROTECT)

class enseigne(TimespantedModel):
    user = models.ForeignKey(Utilisat, models.PROTECT)
    promotion = models.ForeignKey(promotions, models.PROTECT)
    annee = models.ForeignKey(annee, models.PROTECT)
    cours = models.ForeignKey(cours, models.PROTECT)
    ponderaton = models.IntegerField()
    heure = models.IntegerField()
    tp = models.IntegerField(default=0)
    interro = models.IntegerField(default=0)
    categorie = models.IntegerField(choices=categorie,default=1)
    etat=models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Prof. Cours'
        verbose_name_plural = 'Prof. Cours'
        unique_together=['user', 'promotion','cours','annee']

# @receiver(post_save, sender=enseigne)
# def create_etud_prom(sender,instance, **kwargs):
#     if kwargs['created']:
#         pass
#     print(kwargs)

class Droit(models.Model):
    class Meta:
        permissions = (
            ('cotation', 'Menu Cotation'),
            ('transmission', 'Sous Menu Transmission - Cotation'),
            ('deliberation', 'Sous Menu Deliberation - Cotation'),

        )

cote/views.py
import os
import re
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.core.files.storage import FileSystemStorage
from django.db import connection
from django.db.models import Value, CharField, Sum, Max, FloatField, F
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden
from django.shortcuts import render
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
# Create your views here.
from pyreportjasper import JasperPy

from cote.models import exemplaire, etudprom,cote,tempjournalcote,enseigne,delibe
from django.forms import DateInput

from parametrage.models import promotions, annee, cours, sessions, departements


def mentionFinal(pourc, varleger, vargrave, varvide):
    m=''
    if float(pourc)<=50.0:
        m="A"
    else:
        with connection.cursor() as cursor:
            rqttempo='SELECT * from cote_delibe where de<=%s and a>%s'
            cursor.execute(rqttempo, [float(pourc), float(pourc)])
            rows =cursor.fetchall()
            if len(rows) >= 1:
                IH= 0
                i=0
                tot=(len(rows)/4)

                while i<tot:
                    rqt=rqttempo+f' and position=%s and %s{rows[IH][8]}%s and %s{rows[IH+1][8]}%s and %s{rows[IH+2][8]}%s'

                    cursor.execute(rqt, [float(pourc), float(pourc),int(i+1), int(varleger),int(rows[IH][9]), int(vargrave),int(rows[IH+1][9]), int(varvide),int(rows[IH+2][9])])

                    rowst =cursor.fetchall()
                    if len(rowst) >= 1:
                        m=rowst[3][8]
                        break
                    IH += 4
                    i+=1
    return m


def calculerpourcentage(annee,promotion,cours,session,matr):
    listponde={}
    for l in enseigne.objects.filter(promotion_id=promotion,annee_id=annee):
        listponde[l.cours.id]=l.ponderaton


    nbrcours=enseigne.objects.filter(promotion_id=promotion,annee_id=annee).count()
    totponde=enseigne.objects.filter(promotion_id=promotion,annee_id=annee).aggregate(somme=Sum('ponderaton')).get('somme')
    ponde=enseigne.objects.filter(promotion_id=promotion,cours_id=cours,annee_id=annee).aggregate(somme=Sum('ponderaton')).get('somme')
    if ponde is None:
        ponde=0

    if totponde is None:
        totponde=0
    else:
        totponde=totponde*20


    #creation table
    with connection.cursor() as cursor:
        sql = 'CREATE TABLE IF NOT EXISTS "' + str(promotion)+'_'+str(annee) + '" (id serial PRIMARY KEY,matricule VARCHAR (200) UNIQUE NOT NULL,session INT NOT NULL,annee INT NOT NULL,'
        e=enseigne.objects.filter(promotion_id=promotion,annee_id=annee).order_by('-ponderaton').order_by('-heure').order_by('-cours_id')
        for i in e:
            sql += '"'+str(i.cours_id)+'" numeric(10,2) NULL,'
        sql += 'pourc numeric(10,2) NULL,nbrechec INT NULL,nbrechecleger INT NULL,nbrechecgrave INT NULL,nbrevide INT NULL,trav numeric(10,2) NULL,stag numeric(10,2) NULL,mention VARCHAR (2) NULL,mention2 VARCHAR (2) NULL)'
        cursor.execute(sql)
    # creation table

    ##################################recuperer moyen interro/tp
    numinterro=cote.objects.filter(matricule_id=matr,promotion_id=promotion,annee_id=annee,cours_id=cours,sesionn="5").aggregate(nbr=Max('numero')).get('nbr')
    if numinterro is None:
        numinterro=0

    moyinterro=cote.objects.filter(matricule_id=matr,promotion_id=promotion,annee_id=annee,cours_id=cours,sesionn="5").aggregate(somme=Sum('cote')).get('somme')
    if moyinterro is None:
        moyinterro=0
    else:
        moyinterro=float(moyinterro)/float(numinterro)

    numtp = cote.objects.filter(matricule_id=matr, promotion_id=promotion, annee_id=annee, cours_id=cours,sesionn="4").aggregate(nbr=Max('numero')).get('nbr')
    if numtp is None:
        numtp = 0

    moytp = cote.objects.filter(matricule_id=matr, promotion_id=promotion, annee_id=annee, cours_id=cours,sesionn="4").aggregate(somme=Sum('cote')).get('somme')
    if moytp is None:
        moytp = 0
    else:
        moytp = float(moytp) / float(numtp)


    ##################################recuperer moyen interro/tp

    moyexa = float(0)
    somme = float(0)

    if session==4 or session==5:#Tp and Interro
        moyexa1 = cote.objects.filter(matricule_id=matr,promotion_id=promotion,annee_id=annee,cours_id=cours,sesionn="1").aggregate(somme=Sum('cote')).get('somme')#mi-session note
        if moyexa1 is None:
            moyexa1 = 0
        moyexa2 = cote.objects.filter(matricule_id=matr,promotion_id=promotion,annee_id=annee,cours_id=cours,sesionn="2").aggregate(somme=Sum('cote')).get('somme')#1er session note
        if moyexa2 is None:
            moyexa2 = 0
        moyexa3 = cote.objects.filter(matricule_id=matr,promotion_id=promotion,annee_id=annee,cours_id=cours,sesionn="3").aggregate(somme=Sum('cote')).get('somme')#2eme session note
        if moyexa3 is None:
            moyexa3 = 0

        somme1 = float(moyexa1)+float(moyinterro)+float(moytp)
        totgen1 = somme1*float(ponde)
        somme2 =  float(moyexa2)+float(moyinterro)+float(moytp)
        somme3 =  float(moyexa3)+float(moyinterro)+float(moytp)

        #update/add------------------------------------------------

        varvide=varleger=vargrave=0
        mention=''
        pourc=float(0)
        tot=float(0)

        with connection.cursor() as cursor:
            cursor.execute('SELECT * FROM "' + str(promotion)+'_'+str(annee) + '" WHERE matricule = %s and annee = %s and session =1', [matr,annee])
            if cursor.rowcount>=1:
                cursor.execute('UPDATE "' + str(promotion)+'_'+str(annee) + '" SET ' + cours+ ' = %s WHERE matricule = %s and annee = %s and session =1', [somme1,matr,annee])

            cursor.execute('SELECT * FROM "' + str(promotion)+'_'+str(annee) + '" WHERE matricule = %s and annee = %s and session =2',[matr, annee])
            if cursor.rowcount >= 1:
                cursor.execute('UPDATE "' + str(promotion)+'_'+str(annee) + '" SET ' + cours+ ' = %s WHERE matricule = %s and annee = %s and session =2', [somme2,matr,annee])

            cursor.execute('SELECT * FROM "' + str(promotion)+'_'+str(annee) + '" WHERE matricule = %s and annee = %s and session =3',[matr, annee])
            if cursor.rowcount >= 1:
                cursor.execute('UPDATE "' + str(promotion)+'_'+str(annee) + '" SET ' + cours+ ' = %s WHERE matricule = %s and annee = %s and session =3', [somme3,matr,annee])

            ##################################################----------------------------mi-session
            cursor.execute('SELECT * FROM "' + str(promotion)+'_'+str(annee) + '" WHERE matricule = %s and annee = %s and session =1',[matr, annee])
            if cursor.rowcount >= 1:
                cmp= nbrcours+4

                varvide = 0
                vargrave = 0
                varleger = 0
                tot=float(0)
                records = cursor.fetchall()
                columns = cursor.description
                i=4
                while i<cmp:
                    if records[0][i] is None:
                        varvide += 0
                    else:
                        ponderationcours=enseigne.objects.filter(promotion_id=promotion,cours_id=int(columns[i][0]),annee_id=annee).aggregate(somme=Sum('ponderaton')).get('somme')
                        if ponderationcours is None:
                            ponderationcours=0
                        tot += float(records[0][i]) * float(ponderationcours)
                        if float(records[0][i]) >= 0 and float(records[0][i]) <= 7.9:
                            vargrave += 1
                        elif float(records[0][i]) >= 8 and float(records[0][i]) <= 10:
                            varleger += 1
                    i+=1
                pourc = float(tot * 100) / float(totponde)
                mention = mentionFinal(pourc, varleger, vargrave, varvide)
                cursor.execute('update "' + str(promotion) + '_' + str(annee) + '" set pourc=%s,nbrechec=%s,nbrechecleger=%s,nbrechecgrave=%s,nbrevide=%s,mention=%s where matricule=%s and session=%s and annee=%s',[ pourc, (varleger + vargrave), varleger, vargrave, varvide, mention,matr, 1, annee])
                return True
            else:
                pourc = float(totgen1 * 100) / float(totponde)
                varvide = nbrcours-1
                vargrave = 0
                varleger = 0

                if somme1 >= 0 and somme1 <= 7.9:
                    vargrave += 1
                elif somme1 >= 8 and somme1 <= 10:
                    varleger += 1
                mention = mentionFinal(pourc, varleger, vargrave, varvide)
                cursor.execute('insert into "' + str(promotion) + '_' + str(annee) + '" (matricule,session,annee,pourc,nbrechec,nbrechecleger,nbrechecgrave,nbrevide,mention,"' + str(cours) + '") values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)',[matr,1,annee,pourc,(varleger + vargrave),varleger,vargrave,varvide,mention,somme1])
                return True
            ##################################################----------------------------mi-session

            ##################################################----------------------------1er-session
            cursor.execute('SELECT * FROM "' + str(promotion) + '_' + str(
                annee) + '" WHERE matricule = %s and annee = %s and session =2', [matr, annee])
            if cursor.rowcount >= 1:
                cmp = nbrcours + 4

                varvide = 0
                vargrave = 0
                varleger = 0
                tot = float(0)
                records = cursor.fetchall()

cote/templates/cote/deliberation.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock %}


{% block content %}

 <div class="container-fluid pt-4 px-4">
                <div class="row vh-50 bg-secondary rounded align-items-center justify-content-center mx-0">
                   <div class="col-sm-12 col-xl-12">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Déliberation</h6>

                            <div class="bg-secondary rounded h-100 p-4">
                             <nav>
                                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                    <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Liste</button>
                                    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Décision</button>
{#                                    <button class="nav-link" id="nav-etudiant-tab" data-bs-toggle="tab" data-bs-target="#nav-etudiant" type="button" role="tab" aria-controls="nav-etudiant" aria-selected="false">Saisie par Etudiant</button>#}
                                </div>
                            </nav>


                                <div class="tab-content pt-3" id="nav-tabContent">
                                <div class="tab-pane fade active show" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                                    {% include 'cote/saisiedeliberation.html' %}
                                </div>
                                <div class="tab-panes fade"  id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                                    {% include 'cote/saisieprofil.html' %}
                                </div>
                               </div>

                        </div>


                        </div>
                    </div>
                </div>
 </div>

{% endblock %}


 {% block script %}

    <script>


$(document).ready(function() {

     $('.select').select2();

$('body').on('change', '.edit_detect2', function(event){
            var ids = $(this).data('cours');
            var session = $(this).data('session');
            var matricule = $(this).data('matricule');
            var vl = $(this).val();
            var valo = $(this);
         $.ajax({
                url: "{% url 'cote:cote' %}",
                method: "post",
                data: {
                    "matricule": matricule,
                    "csrfmiddlewaretoken": '{{ csrf_token }}',
                    "cote": vl,
                    'numero':$('#numero').val(),
                    'cours':ids,
                    'epreuve':session,
                    'annee':$('#annee').val(),
                    "promotion":$('#promotion').val()
                },
                dataType: "json",
                success: function(data){

                    if(data.id=='1'){
                        $.toast({
                                    heading: 'Information',
                                    text: data.msg,
                                    icon: 'success',
                                    loader: true,        // Change it to false to disable loader
                                    loaderBg: '#9EC600'  // To change the background
                                })

                    }else{
                          $.toast({
                                    heading: 'Erreur',
                                    text: data.msg,
                                    icon: 'error',
                                    loader: true,        // Change it to false to disable loader
                                    loaderBg: '#9EC600'  // To change the background
                                });
                    }


                },
                        error: function(request, status, err) {

                               $.toast({
                                    heading: 'Erreur',
                                    text: request + status + err,
                                    icon: 'error',
                                    loader: true,        // Change it to false to disable loader
                                    loaderBg: '#9EC600'  // To change the background
                                });
                        }
            });

    });


afficher();


                 $('#promotion,#epreuve,#annee').on('change', function()
                    {

                        afficher();


                    });





});
function modaldelibe(id,nom,postnom,pourcentage,mention,nbrechec,nbrechecleger,nbrechecgrave,nbrevide) {
                        afficher2(id);
                        var lbl=nom+' '+postnom +' Pourc: '+pourcentage+' Mention: '+mention+' Ech: '+nbrechec+' EchL: '+nbrechecleger+' EchG: '+nbrechecgrave+' Vide: '+nbrevide+' Session: '+$('#epreuve option:selected').text();
                         $('#etudiantid').html(lbl);
                         $('#nav-profile-tab').click();

}


 function afficher()
    {


    try{

    var oTABLE=$('#example').DataTable({
    "bProcessing":true,
        language: {
                url: "{% static 'css/fr_fr.json' %}"
            },
        ajax: {
            url: '{% url 'cote:listdeliberation' %}',
            type: 'get',
            data: {
                    'epreuve':$('#epreuve').val(),
                    'annee':$('#annee').val(),
                    "promotion":$('#promotion').val()
                }
        },
    "columns":[

    {"data":'matricule_id',"autoWidth":true,"render":function (data){
            return data ;

        }},
    {"data":'nom'},

    {"data":'postnom'},
    {"data":'pourcentage'},
    {"data":'mention'},
    {"data":'nbrechec'},
    {"data":'nbrechecleger'},
    {"data":'nbrechecgrave'},
    {"data":'nbrevide'},
    {"data":'matricule_id',"autoWidth":true,"render":function (data, type, row, meta){

            return "{% if perms.cote.deliberation %}<button onclick=modaldelibe('"+ row.matricule_id+"','"+row.nom+"','"+row.postnom+"','"+row.pourcentage+"','"+row.mention+"','"+row.nbrechec+"','"+row.nbrechecleger+"','"+row.nbrechecgrave+"','"+row.nbrevide+"') title='voir'><i class='fa fa-eye' style='color: green'></i></button>{% endif %}" ;

        }}


    ],

    "bDestroy":true
    });
    }catch(e){
       //alert(e)
    }
    }


    function afficher2(id)
    {


    try{

    var oTABLEE=$('#example2').DataTable({
    "bProcessing":true,
        language: {
                url: "{% static 'css/fr_fr.json' %}"
            },
     "ordering": false,
    "pageLength": 50,
        ajax: {
            url: '{% url 'cote:listdeliberationone' %}',
            type: 'get',
            data: {
                    'epreuve':$('#epreuve').val(),
                    'annee':$('#annee').val(),
                    'numero':$('#numero').val(),
                    'matricule':id,
                    "promotion":$('#promotion').val()
                }
        },
    "columns":[

    {"data":'cours__sigle',"autoWidth":true,"render":function (data){
            return data ;

        }},
    {"data":'note',"autoWidth":true,"render":function (data, type, row, meta){

        if (row.cours__enseigne__categorie==1)
            return "{% if perms.cote.deliberation %}<input style='background:#0d6efd;color:white;' type='text' data-cours="+ row.cours_id +" data-matricule="+ id +"  data-session="+ row.sesionn +" value='"+ row.cote+"' class='form-control edit_detect2'>{% else %}"+ row.cote +"{% endif %}" ;
        else if (row.cours__enseigne__categorie==2)
            return "{% if perms.cote.deliberation %}<input style='background:#a41515;color:white;' type='text' data-cours="+ row.cours_id +" data-matricule="+ id +"  data-session="+ row.sesionn +" value='"+ row.cote+"' class='form-control edit_detect2'>{% else %}"+ row.cote +"{% endif %}" ;
        else
            return "{% if perms.cote.deliberation %}<input style='background:#b6effb;color:black;' type='text' data-cours="+ row.cours_id +" data-matricule="+ id +"  data-session="+ row.sesionn +" value='"+ row.cote+"' class='form-control edit_detect2'>{% else %}"+ row.cote +"{% endif %}" ;



        }}


    ],

    "bDestroy":true
    });
    }catch(e){
       //alert(e)
    }
    }

    </script>
{% endblock %}

cote/templates/cote/saisiecompose.html
 <form>


                                <div class="mb-3">

                                    <div class="row">
                                    <div class="col-sm-2">
                                    <label class="form-label">Categorie</label>
                                    <select class="form-control select" id="categorie" name="categorie">
                                        <option value="1">Cours</option>
                                        <option value="2">Etudiant</option>

                                    </select>

                                    </div>
                                    <div class="col-sm-2">
                                    <label class="form-label">Annee Academique</label>
                                    <select class="form-control select" id="annee2" name="annee2">
                                        {% for foo in annee %}
                                        <option value="{{ foo.id }}">{{ foo.libelle }}</option>
                                        {% endfor %}


                                    </select>

                                    </div>

                                    <div class="col-sm-2">
                                        <label for="exampleInputEmail1" class="form-label">Promotion</label>
                                        <select class="form-control select" id="promotion2" name="promotion2">
                                            {% for foo in promotion %}
                                            <option value="{{ foo.id }}">{{ foo.libelle }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-sm-5">
                                        <label for="exampleInputEmail1" class="form-label" id="lblce">Cours ou Etudiant</label>
                                        <select class="form-control select" id="etudiant_cours" name="etudiant_cours">

                                        </select>
                                    </div>
                                     <div class="col-sm-1">
                                        <label for="exampleInputEmail1" class="form-label">N° Epr.</label>
                                        <input type="number" class="form-control" value="1" name="numero2" id="numero2">

                                    </div>
                                    </div>
                                    &nbsp;
                                    <div class="row">
                                    <div class="col-sm-6">
                                   {% if perms.cote.view_cote %} <button  type="button" id="btnaff2" class="btn btn-primary">Afficher</button>{% endif %}

                                    </div>

                                    </div>

                                </div>

</form>
                                     <div class="accordion" id="accordionExample">
                                <div class="accordion-item bg-transparent">
                                    <h2 class="accordion-header" id="headingOne">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                            Liste Cote des Etudiants

                                        </button>



                                    </h2>


                                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
                                        <div class="accordion-body">

                                            <div class="table-responsive">
                                                <table id="example2" class="table table-hover dataTable table-striped table_custom border-style spacing5">
                                                    <thead id="thbody">

                                                    </thead>
                                                    <tbody style="color: white" id="tbbody">
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

cote/templates/cote/saisieprofil.html
<div class="col-sm-12 col-xl-6">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Etudiant : <span id="etudiantid"></span></h6>
                            <h6 class="mb-4" style="color: #0d6efd;">Les matières de formation professionnelle</h6>
                            <h6 class="mb-4" style="color: #a41515;">Les matières d'appuie à la formation professionnelle</h6>
                            <h6 class="mb-4" style="color: #b6effb;">Les matières de formation générale</h6>
                        </div>
                         <div class="table-responsive" >
                                                <table id="example2" class="table table-hover dataTable table-striped table_custom border-style spacing5">
                                                    <thead>
                                                        <tr>
                                                        <th>Cours</th>
                                                        <th>Point</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody id="txtbody2"></tbody>

                                                </table>
                                            </div>
</div>