cote/urls.py
from django.urls import path, include
from .views import *
from . import views
app_name='cote'
urlpatterns = [

    path('exemplaire/', views.ExemplaireListView.as_view(permission_required='cote.view_exemplaire'),name='exemplaire'),
    path('exemplaire/<int:pk>/detail', views.ExemplaireDetailView.as_view(permission_required='cote.view_exemplaire'),name='exemplaire_detail'),
    path('exemplaire/create/', views.ExemplaireCreateView.as_view(permission_required='cote.add_exemplaire'),name='exemplaire_create'),
    path('exemplaire/<int:pk>/update/',views.ExemplaireUpdateView.as_view(permission_required='cote.change_exemplaire'), name='exemplaire_update'),
    path('exemplaire/<int:pk>/delete/',views.ExemplaireDeleteView.as_view(permission_required='cote.delete_exemplaire'), name='exemplaire_delete'),

    path('cote/', views.CoteListView.as_view(permission_required='cote.view_cote'),name='cote'),
    # path('cote/<int:pk>/detail', views.CoteDetailView.as_view(permission_required='cote.view_cote'),name='cote_detail'),
    # path('cote/create/', views.CoteCreateView.as_view(permission_required='cote.add_cote'),name='cote_create'),
    # path('cote/<int:pk>/update/',views.CoteUpdateView.as_view(permission_required='cote.change_cote'), name='cote_update'),
    # path('cote/<int:pk>/delete/',views.CoteDeleteView.as_view(permission_required='cote.delete_cote'), name='cote_delete'),

    path('deliberation/',deliberation, name='deliberation'),
    path('listdeliberation/',listdeliberation, name='listdeliberation'),
    path('listdeliberationone/',listdeliberationone, name='listdeliberationone'),

    path('addfile/',addfile, name='addfile'),
    path('corriger/',corriger, name='corriger'),
    path('deletefile/',deletefile, name='deletefile'),

]

parametrage/urls.py
from django.urls import path, include
from .views import *
from . import views
app_name='parametrage'




urlpatterns = [

    path('', check, name="check"),
    path('uncheck/', uncheck, name="uncheck"),
    path('home', TemplateMain.as_view(template_name='base.html'),name='home'),

    path('etudiants/', views.EtudiantsListView.as_view(permission_required='parametrage.view_etudiants'), name='etudiants'),
    path('etudiants/<int:pk>/detail', views.EtudiantsDetailView.as_view(permission_required='parametrage.view_etudiants'),name='etudiants_detail'),
    path('etudiants/create/', views.EtudiantsCreateView.as_view(permission_required='parametrage.add_etudiants'),name='etudiants_create'),
    path('etudiants/<int:pk>/update/', views.EtudiantsUpdateView.as_view(permission_required='parametrage.change_etudiants'), name='etudiants_update'),
    path('etudiants/<int:pk>/delete/', views.EtudiantsDeleteView.as_view(permission_required='parametrage.delete_etudiants'),name='etudiants_delete'),




]

univa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parametrage.urls'), name='parametrage'),
    path('', include('cote.urls'), name='cote'),
    path('', include('inscription.urls'), name='inscription'),
    path('', include('paiement.urls'), name='inscription'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parametrage/models.py
from django.contrib.auth.models import User, AbstractUser
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models import Q

sessions = (
    ("1","Mi-Session"),
    ("2","1ere Session"),
    ("3","2eme Session"),
    ("5","Interro"),
    ("4","Tp"),
    ("6","Session Special"),
    )

class TimespantedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True

Sexe = (
    ("F","Feminin"),
    ("M","Masculin")
    )
Etatcivil = (
    ("C","Célibataire"),
    ("M","Marié")
    )



class Utilisat(AbstractUser):
    sexe = models.CharField(choices=Sexe, max_length=255)

class universite(TimespantedModel):
    pays = models.CharField(max_length=50)
    ministere=models.CharField(max_length=255,default="Ministere de l'Enseignement Superieur et Universitaire")
    ville = models.CharField(max_length=50)
    commune = models.CharField(max_length=50)
    nom = models.CharField(max_length=255)
    sigle = models.CharField(max_length=50)
    siteweb = models.CharField(max_length=50)
    upload=models.ImageField(upload_to='logo_images',blank=True,null=True)
    def __str__(self):
        return self.nom
    class Meta:
        verbose_name = 'Univesité'
        verbose_name_plural = 'Univesités'

class annee(TimespantedModel):
    libelle = models.CharField(max_length=9,unique=True)
    etat = models.BooleanField(default=False)
    def __str__(self):
        return self.libelle
    class Meta:
        verbose_name = 'Annee'
        verbose_name_plural = 'Annees'

# class sessions(TimespantedModel):
#     libelle = models.CharField(max_length=100)
#     etat = models.BooleanField(default=True)
#     def __str__(self):
#         return self.libelle
#     class Meta:
#         verbose_name = 'Session'
#         verbose_name_plural = 'Sessions'


class departements(TimespantedModel):
    libelle = models.CharField(max_length=100)
    etat = models.BooleanField(default=True)
    def __str__(self):
        return self.libelle
    class Meta:
        verbose_name = 'Departement'
        verbose_name_plural = 'Departements'

class sections(TimespantedModel):
    libelle = models.CharField(max_length=100)
    departement = models.ForeignKey(departements, models.PROTECT)
    etat = models.BooleanField(default=True)
    def __str__(self):
        return self.libelle
    class Meta:
        verbose_name = 'Section'
        verbose_name_plural = 'Sections'

class options(TimespantedModel):
    libelle = models.CharField(max_length=100)
    section = models.ForeignKey(sections, models.PROTECT)
    etat = models.BooleanField(default=True)
    def __str__(self):
        return self.libelle
    class Meta:
        verbose_name = 'Option'
        verbose_name_plural = 'Options'

class promotions(TimespantedModel):
    libelle = models.CharField(max_length=100)
    option = models.ForeignKey(options, models.PROTECT)
    etat = models.BooleanField(default=True)
    type= models.IntegerField(default=0)
    def __str__(self):
        return self.libelle
    class Meta:
        verbose_name = 'Promotion'
        verbose_name_plural = 'Promotions'

class cours(TimespantedModel):
    libelle = models.CharField(max_length=255,unique=True)
    sigle = models.CharField(max_length=10,unique=True)
    etat = models.BooleanField(default=True)

    def __str__(self):
        return self.libelle
    class Meta:
        verbose_name = 'Cours'
        verbose_name_plural = 'Cours'

class etudiants(TimespantedModel):
    matricule = models.CharField(max_length=50,unique=True)
    nom = models.CharField(max_length=50)
    postnom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50,blank=True, null=True)
    sexe = models.CharField(choices=Sexe,max_length=1,default='M',blank=True, null=True)
    etat_civil = models.CharField(choices=Etatcivil, max_length=20,default='C',blank=True, null=True)
    telephone = models.CharField(max_length=15,blank=True, null=True)
    adresse = models.CharField(max_length=155, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    date_naissance = models.DateField(blank=True, null=True)
    lieu_naissance = models.CharField(max_length=100, blank=True, null=True)
    etat = models.BooleanField(default=True)
    user=models.ForeignKey(Utilisat, models.PROTECT,blank=True, null=True)

    def __str__(self):
        return self.nom



class Droit(models.Model):
    class Meta:
        permissions=(
            # ('cotation','Onglet Cotation'),

            # # ('rapport','Onglet Rapport'),
            # ('validation','Validateur'),
            # ('inscrit','Etudiant Valide'),
            # # ('paiement','Onglet Paiement'),
            # # ('presence','Onglet Presence'),
            # # ('depense','Onglet Depense'),
            # # ('conge','Onglet Conge'),
            # # ('rh','Onglet RH'),
            # # ('evaluation','Onglet Evaluation'),
            # # ('tableau','Onglet Tableau'),
            # ('noteobtenue','Onglet Note obtenue acad.'),
            # ('noteobtenueetudiant','Onglet Note obtenue Etud.'),
            #
            #
            # ('tablobord','Menu tableau de Bord'),
            # ('apropoetu','Menu Etudiant profil'),
            # ('apropoprof','Menu Professeur profil'),
            #
            # ('listetud','Menu liste Etudiant'),
            # ('listetudordre','Menu liste Etudiant ordre'),
            # ('listetudlitige','Menu liste Etudiant litige'),
            # ('inscrits','Menu Etudiant inscrit'),
            # ('noninscrits','Menu  Etudiant en cours inscription'),
            # ('nonconforme','Menu Etudiant inscrit non conform'),
            #
            # ('programme','Menu Programme'),
            # ('emailling','Menu Emailling'),
            # ('grh','Menu Gestion RH'),
            # ('etudiants','Menu Etudiant'),
            # ('rap','Menu Rapport'),
            # ('archivage','Menu Archivages'),
            # ('bibliotheque','Menu Biblioteque'),
            # ('finance','Menu Finances'),




        )
# class UserPermission(models.Model):
#     id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
#     userid = models.ForeignKey('Utilisateur', models.DO_NOTHING, db_column='UserId', blank=True, null=True)  # Field name made lowercase.
#     permissionid = models.ForeignKey(Permission, models.DO_NOTHING, db_column='PermissionId', blank=True, null=True)  # Field name made lowercase.
#     active = models.BooleanField(db_column='Active', blank=True, null=True)  # Field name made lowercase.
#
#     class Meta:
#         managed = True
#         db_table = 'USER_PERMISSION'
#
#
# class Utilisateur(models.Model):
#     utilisateur_id = models.AutoField(db_column='Utilisateur_Id', primary_key=True)  # Field name made lowercase.
#     utilisateur_prenom = models.CharField(db_column='Utilisateur_Prenom', max_length=150, blank=True, null=True)  # Field name made lowercase.
#     utilisateur_login = models.CharField(db_column='Utilisateur_Login', max_length=150, blank=True, null=True)  # Field name made lowercase.
#     utilisateurspassword = models.CharField(db_column='UtilisateursPassword', max_length=150, blank=True, null=True)  # Field name made lowercase.
#     utilisateur_nomcomplet = models.CharField(db_column='utilisateur_NomComplet', max_length=150, blank=True, null=True)  # Field name made lowercase.
#     utilisateur_valide = models.BooleanField(db_column='Utilisateur_Valide', blank=True, null=True)  # Field name made lowercase.
#     utilisateur_date_creation = models.DateField(db_column='Utilisateur_Date_Creation', blank=True, null=True)  # Field name made lowercase.
#     roleid = models.ForeignKey(Roles, models.DO_NOTHING, db_column='RoleId', blank=True, null=True)  # Field name made lowercase.
#     adresse = models.CharField(db_column='Adresse', max_length=255, blank=True, null=True)  # Field name made lowercase.
#     telephone = models.CharField(db_column='Telephone', max_length=15, blank=True, null=True)  # Field name made lowercase.
#     email = models.CharField(db_column='Email', max_length=25, blank=True, null=True)  # Field name made lowercase.
#     isdeleted = models.BooleanField(db_column='IsDeleted', blank=True, null=True)  # Field name made lowercase.
#
#     class Meta:
#         managed = True
#         db_table = 'UTILISATEUR'

parametrage/templates/parametrage/etudiants_detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock %}


{% block content %}

 <div class="container-fluid pt-4 px-4">
                <div class="row vh-50 bg-secondary rounded align-items-center justify-content-center mx-0">
                   <div class="col-sm-12 col-xl-12">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Etudiant <a style="float: right" href="{% url 'parametrage:etudiants' %}" class="btn btn-outline-warning">Retour</a>&nbsp;</h6>


                            <div class="row justify-content-center">
   <div class="col-md-7 col-lg-4 mb-5 mb-lg-0 wow fadeIn">
      <div class="card border-0 shadow">
         <img src="{% static 'img/avatar.jpg' %}" alt="...">
         <div class="card-body p-1-9 p-xl-5">
            <div class="mb-4">
               <h3 class="h4 mb-0" style="color: #0c4128">{{ etudiants.nom }}</h3>
               <span class="text-primary">{{ etudiants.postnom }}, {{ etudiants.prenom }}</span>
            </div>
            <ul class="list-unstyled mb-4">
               <li class="mb-3"><a href="#!"><i class="far fa-envelope display-25 me-3 text-secondary"></i>{{ etudiants.mail }}</a></li>
               <li class="mb-3"><a href="#!"><i class="fas fa-mobile-alt display-25 me-3 text-secondary"></i>{{ etudiants.telephone }}</a></li>
               <li><a href="#!"><i class="fas fa-map-marker-alt display-25 me-3 text-secondary"></i>{{ etudiants.adresse }}</a></li>
            </ul>

         </div>
      </div>
   </div>
   <div class="col-lg-8">
      <div class="ps-lg-1-6 ps-xl-5">
         <div class="mb-5 wow fadeIn">
            <div class="text-start mb-1-6 wow fadeIn">
               <h2 class="h1 mb-0 text-primary">#Informations</h2>
            </div>
            <p>
                <div class="col-sm-12 col-xl-12">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4"></h6>
                            <ul class="list-group">
                                <li class="list-group-item bg-transparent">Sexe : {{ etudiants.sexe }}</li>
                                <li class="list-group-item bg-transparent">Etat civil : {{ etudiants.etat_civil }}</li>
                                <li class="list-group-item bg-transparent">Lieu Naiss. : {{ etudiants.lieu_naissance }}</li>
                                <li class="list-group-item bg-transparent">Date Naiss. : {{ etudiants.date_naissance }}</li>
                            </ul>
                        </div>
                    </div>
            </p>

         </div>
         <div class="accordion" id="accordionExample">
                                <div class="accordion-item bg-transparent">
                                    <h2 class="accordion-header" id="headingOne">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                            Parcours
                                        </button>
                                    </h2>
                                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
                                        <div class="accordion-body">
                                            <div class="col-sm-12 col-xl-12">
                                                <div class="bg-secondary rounded h-50 p-4">

                                                    <ul class="list-group list-group-flush">
                                                        {% for parcour in parcours %}
                                                        <li class="list-group-item bg-transparent">{{ parcour.annee.libelle }} - {{ parcour.promotion.libelle }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item bg-transparent">
                                    <h2 class="accordion-header" id="headingTwo">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                            Cote
                                        </button>
                                    </h2>
                                    <div id="collapseTwo" class="accordion-collapse collapse " aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            Voluptua sit dolores consetetur ea et diam est et takimata. Et erat sadipscing dolores et stet diam ut ut diam, sit aliquyam no magna et dolore lorem dolor sit. Lorem lorem sed sed duo, eirmod sit diam ipsum sit erat, lorem sit dolor diam amet ea aliquyam tempor rebum invidunt,.
                                        </div>
                                    </div>
                                </div>
                            </div>
      </div>
   </div>
</div>
                        </div>
                    </div>
                </div>
 </div>

{% endblock %}


 {% block script %}

    <script>

$(document).ready(function() {

     $('.select').select2();
     $('.js-basic-example').DataTable({
            language: {
                url: "{% static 'css/fr_fr.json' %}"
            }
        });






});

{#function addImages(id) {#}
{#  var files = $("#files").prop("files");#}
{#  var file = files[loopGallery];#}
{#  var cList = files.length;#}
{##}
{#  var fd = new FormData();#}
{#  fd.append("file", file);#}
{#  fd.append("galerie", id);#}
{##}
{#  var xhr = new XMLHttpRequest();#}
{#  xhr.open("POST", "moduls/galerie/uploadimages.php", true);#}
{#  xhr.upload.onprogress = function(e) {#}
{#    var percentComplete = Math.ceil((e.loaded / e.total) * 100);#}
{#    $("#progress").css("display","");#}
{#    $("#progressText").text((loopGallery+1)+" z "+cList);#}
{#    $("#progressBar").css("width",percentComplete+"%");#}
{#  };#}
{##}
{#  xhr.onload = function() {#}
{#    if(this.status == 200) {#}
{#      $("#progressObsah").load("moduls/galerie/showimages.php?ids="+id);#}
{#      if((loopGallery+1) == cList) {#}
{#        loopGallery = 0;#}
{#      } else {#}
{#        $("#progressBar").css("width", "0%");  #}
{#        loopGallery++;#}
{#        addImages(id);#}
{#      }#}
{#    }#}
{#  }#}
{##}
{#  if(cList > 0) {#}
{#    xhr.send(fd);#}
{#  }#}
{#}#}



    </script>
{% endblock %}

parametrage/templates/parametrage/etudiants_form.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock %}


{% block content %}

 <div class="container-fluid pt-4 px-4">
                <div class="row vh-50 bg-secondary rounded mx-0">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Ajout Etudiant</h6>
                            <form method="post" >
                            {% csrf_token %}
                                {% if not update %}
                                         <div class="row mb-3">

                                    <div class="col-sm-2">

                                           <label class="form-label">Annee Academique</label>
                                            <select class="form-control select" id="annee" name="annee" {% if anneeid %}{% if foo.id == anneeid %}readonly{% endif %}{% endif %}>
                                                {% for foo in annee %}
                                                <option value="{{ foo.id }}" {% if anneeid %}{% if foo.id == anneeid %}selected{% endif %}{% endif %}>{{ foo.libelle }}</option>
                                                {% endfor %}


                                            </select>
                                    </div>
                                     <div class="col-sm-2">
                                        <label for="exampleInputEmail1" class="form-label">Departement</label>
                                        <select onchange="getsections(this)" class="form-control select" id="departement" name="departement">
                                            {% for foo in departement %}
                                            <option value="{{ foo.id }}">{{ foo.libelle }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>

                                    <div class="col-sm-2">
                                        <label for="exampleInputEmail1" class="form-label">Sections</label>
                                        <select onchange="getoptions(this)" class="form-control select" id="section" name="section">

                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <label for="exampleInputEmail1" class="form-label">Options</label>
                                        <select onchange="getpromotion(this)"  class="form-control select" id="option" name="option">

                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <label for="exampleInputEmail1" class="form-label">Promotion</label>
                                        <select  class="form-control required select" id="promotion" name="promotion">

                                        </select>
                                    </div>
                                </div>
                                {% endif %}

                                <div class="row mb-3">
                                    <label for="inputEmail3" class="col-sm-2 col-form-label">{{ form.matricule.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.matricule }}
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.nom.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.nom }}
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.postnom.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.postnom }}
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.prenom.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.prenom }}
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.sexe.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.sexe }}
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.etat_civil.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.etat_civil }}
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.date_naissance.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.date_naissance }}
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.lieu_naissance.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.lieu_naissance }}
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.telephone.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.telephone }}
                                    </div>
                                </div>
                                 <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.adresse.label }}</label>
                                    <div class="col-sm-10">
                                        {{ form.adresse }}
                                    </div>
                                </div>
                            <div class="row mb-3">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Etat</label>
                                    <div class="col-sm-10">
                                        <input class="form-check-input m-0" checked name="etat" id="id_etat" type="checkbox">

                                    </div>
                                </div>

                                <div class="col-sm-12">
                                <button type="submit" class="btn btn-primary" name="_addanother">Enregistrer et ajouter un autre </button>
                                <button type="submit" class="btn btn-danger" name="_continue">Enregistrer et continuer l'édition </button>
                                <button type="submit" class="btn btn-success" name="_save">Enregistrer</button>
                                <button type="button" onclick="window.location='{% url 'parametrage:etudiants' %}'; return false;" class="btn btn-outline-warning">Voir la liste</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
 </div>

{% endblock %}


 {% block script %}

    <script>
$(document).ready(function() {

     $('.select').select2();
     $('.js-basic-example').DataTable({
            language: {
                url: "{% static 'css/fr_fr.json' %}"
            }
        });
      $('#departement').change();


});






    </script>
{% endblock %}

parametrage/templates/parametrage/typefrais_confirm_delete.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="section-body">
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center ">
<div class="header-action">
<h1 class="page-title">SUPPRIMER TYPE FRAIS</h1>

</div>
</div>
</div>
</div>


<div class="section-body mt-4">
<div class="container-fluid">
    <div class="tab-content">
<div class="tab-pane active" id="Dep-add">
<div class="col-lg-12 col-md-12">


{% url 'parametrage:typefrais' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">SUPPRESSION TYPE FRAIS</h1>

        <p class="h5">Voulez-vous vraiment supprimer :</p>
        <h3 class="my-5">{{ typefrais.libelle }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirmer" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Annuler">
        </form>
    </div>
</div>

</div>
</div>

    </div>
</div>
</div>
    
    
{% endblock %}